# Rule-based personas → ad asset mapping
# The first matching rule wins.
personas:
  - name: kids_male
    when:
      max_age: 12
      gender: male
    ad: ui/assets/ads/kids_male_video.mp4

  - name: kids_female
    when:
      max_age: 12
      gender: female
    ad: ui/assets/ads/kids_female_video.mp4

  - name: adult_male
    when:
      min_age: 13
      gender: male
    ad: ui/assets/ads/adult_male_video.mp4

  - name: adult_female
    when:
      min_age: 13
      gender: female
    ad: ui/assets/ads/adult_female_video.mp4

defaults:
  ad: ui/assets/ads/fallback.jpg
